package itmo.blps.model;

public enum Permission {
    VIEW_ALL_PAID_ORDERS,
    VIEW_ALL_CONFIRMED_ORDERS,
    VIEW_ALL_ADDRESSES,
    VIEW_ALL_PRODUCTS,
    VIEW_PRODUCT,
    VIEW_CURRENT_ORDER,
    VIEW_CURRENT_ADDRESSES,
    PAY_ORDER,
    CREATE_ADDRESS,
    SET_ADDRESS,
    CONFIRM_ORDER,
    ADD_PRODUCT,
    CREATE_CARD,
    TOP_UP_BALANCE,
    REGISTER,
    LOGIN,
    VIEW_USERS,
    EDIT_USERS,
    DELETE_USERS
}